# Generated by Django 4.1.7 on 2023-03-04 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='F_inicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha inicio ciclos')),
            ],
            options={
                'verbose_name': 'Fecha inicio ciclos',
                'verbose_name_plural': 'Fecha inicio ciclos',
            },
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='Título')),
                ('sesion', models.SmallIntegerField(verbose_name='Sesión')),
                ('dias_numero', models.CharField(blank=True, max_length=19, null=True, verbose_name='Días número')),
                ('detalles', models.TextField(blank=True, null=True, verbose_name='Detalles')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tema',
                'verbose_name_plural': 'Temas',
            },
        ),
    ]
